/**
 * Maps headline keywords to Lucide icon names.
 * Uses the actual Lucide library (1,800+ icons) instead of hand-coded shapes.
 *
 * The mapping is organized by category. Multiple keywords can map to the same icon.
 * Keywords are matched case-insensitively against headline text.
 */

/**
 * Keyword → Lucide icon name.
 * Ordered by specificity (longer/more-specific keywords first within categories).
 */
const KEYWORD_ICONS: [string, string][] = [
    // ── Conflict / War ──
    ['missile', 'rocket'],
    ['invasion', 'swords'],
    ['military', 'shield'],
    ['soldier', 'shield'],
    ['troops', 'shield'],
    ['combat', 'swords'],
    ['battle', 'swords'],
    ['weapon', 'sword'],
    ['attack', 'sword'],
    ['strike', 'sword'],
    ['armor', 'shield'],
    ['bomb', 'bomb'],
    ['war', 'swords'],
    ['army', 'shield'],
    ['drone', 'radar'],
    ['defense', 'shield-check'],
    ['nuclear', 'radiation'],
    ['terror', 'skull'],
    ['siege', 'castle'],
    ['ceasefire', 'handshake'],
    ['airstrike', 'plane'],
    ['artillery', 'target'],
    ['ammunition', 'target'],
    ['guerrilla', 'swords'],
    ['insurgent', 'swords'],
    ['militia', 'shield'],
    ['warhead', 'bomb'],
    ['shelling', 'bomb'],
    ['frontline', 'flag'],

    // ── Economy / Finance ──
    ['inflation', 'trending-up'],
    ['recession', 'trending-down'],
    ['interest rate', 'percent'],
    ['stock market', 'candlestick-chart'],
    ['wall street', 'landmark'],
    ['cryptocurrency', 'bitcoin'],
    ['bitcoin', 'bitcoin'],
    ['crypto', 'bitcoin'],
    ['investment', 'piggy-bank'],
    ['investor', 'briefcase'],
    ['billion', 'banknote'],
    ['million', 'banknote'],
    ['trillion', 'banknote'],
    ['revenue', 'receipt'],
    ['profit', 'trending-up'],
    ['market', 'chart-candlestick'],
    ['stock', 'chart-line'],
    ['economy', 'coins'],
    ['trade', 'globe'],
    ['bank', 'landmark'],
    ['finance', 'wallet'],
    ['dollar', 'dollar-sign'],
    ['price', 'tag'],
    ['tax', 'receipt'],
    ['debt', 'credit-card'],
    ['growth', 'trending-up'],
    ['invest', 'piggy-bank'],
    ['budget', 'calculator'],
    ['gdp', 'chart-bar'],
    ['tariff', 'package'],
    ['export', 'package'],
    ['import', 'package'],
    ['currency', 'coins'],
    ['wage', 'banknote'],
    ['salary', 'banknote'],
    ['unemployment', 'user-x'],
    ['bankruptcy', 'ban'],
    ['merger', 'merge'],
    ['acquisition', 'handshake'],
    ['ipo', 'rocket'],
    ['nasdaq', 'chart-line'],
    ['dow', 'chart-bar'],
    ['treasury', 'landmark'],
    ['federal reserve', 'landmark'],
    ['central bank', 'landmark'],
    ['commodity', 'gem'],
    ['gold', 'gem'],

    // ── Weather / Climate ──
    ['hurricane', 'tornado'],
    ['tornado', 'tornado'],
    ['blizzard', 'snowflake'],
    ['thunderstorm', 'cloud-lightning'],
    ['lightning', 'cloud-lightning'],
    ['wildfire', 'flame'],
    ['forecast', 'cloud-sun'],
    ['temperature', 'thermometer'],
    ['heatwave', 'thermometer-sun'],
    ['storm', 'cloud-lightning'],
    ['flood', 'waves'],
    ['drought', 'sun'],
    ['rain', 'cloud-rain'],
    ['snow', 'snowflake'],
    ['heat', 'thermometer-sun'],
    ['cold', 'snowflake'],
    ['wind', 'wind'],
    ['fog', 'cloud-fog'],
    ['hail', 'cloud-hail'],
    ['monsoon', 'umbrella'],
    ['cyclone', 'tornado'],
    ['frost', 'snowflake'],
    ['fire', 'flame'],

    // ── Health / Medical ──
    ['vaccination', 'syringe'],
    ['vaccine', 'syringe'],
    ['pandemic', 'biohazard'],
    ['outbreak', 'biohazard'],
    ['hospital', 'hospital'],
    ['surgeon', 'stethoscope'],
    ['surgery', 'stethoscope'],
    ['disease', 'bug'],
    ['treatment', 'pill'],
    ['diagnosis', 'stethoscope'],
    ['symptom', 'activity'],
    ['patient', 'heart-pulse'],
    ['health', 'heart-pulse'],
    ['medical', 'cross'],
    ['virus', 'bug'],
    ['covid', 'biohazard'],
    ['drug', 'pill'],
    ['cancer', 'ribbon'],
    ['mental', 'brain'],
    ['wellness', 'heart'],
    ['therapy', 'brain'],
    ['nurse', 'stethoscope'],
    ['clinic', 'hospital'],
    ['pharmaceutical', 'pill'],
    ['antibiotic', 'pill'],
    ['infection', 'bug'],
    ['organ', 'heart'],
    ['transplant', 'heart'],
    ['ambulance', 'ambulance'],
    ['emergency room', 'siren'],
    ['prescription', 'clipboard'],
    ['epidemic', 'biohazard'],
    ['quarantine', 'lock'],
    ['mask', 'venetian-mask'],
    ['blood', 'droplets'],
    ['dna', 'dna'],

    // ── Politics / Government ──
    ['presidential', 'landmark'],
    ['parliament', 'landmark'],
    ['legislation', 'scroll'],
    ['government', 'landmark'],
    ['republican', 'flag'],
    ['democrat', 'flag'],
    ['bipartisan', 'handshake'],
    ['president', 'landmark'],
    ['congress', 'landmark'],
    ['election', 'vote'],
    ['campaign', 'megaphone'],
    ['minister', 'landmark'],
    ['senate', 'landmark'],
    ['vote', 'vote'],
    ['policy', 'scroll'],
    ['debate', 'scale'],
    ['reform', 'scale'],
    ['law', 'gavel'],
    ['veto', 'ban'],
    ['impeach', 'gavel'],
    ['constitution', 'scroll'],
    ['amendment', 'pencil'],
    ['governor', 'landmark'],
    ['mayor', 'landmark'],
    ['cabinet', 'users'],
    ['lobby', 'handshake'],
    ['coalition', 'users'],
    ['opposition', 'swords'],
    ['inauguration', 'crown'],
    ['dictator', 'crown'],
    ['regime', 'shield'],
    ['coup', 'swords'],
    ['ballot', 'vote'],
    ['poll', 'chart-bar'],
    ['approval', 'thumbs-up'],
    ['disapproval', 'thumbs-down'],
    ['corruption', 'ban'],
    ['scandal', 'alert-triangle'],
    ['whistleblower', 'megaphone'],
    ['protest', 'megaphone'],
    ['rally', 'users'],
    ['demonstration', 'users'],
    ['activist', 'megaphone'],
    ['sanction', 'ban'],

    // ── Technology ──
    ['artificial intelligence', 'brain-circuit'],
    ['machine learning', 'brain-cog'],
    ['autonomous', 'bot'],
    ['blockchain', 'link'],
    ['cybersecurity', 'shield-check'],
    ['algorithm', 'code'],
    ['microsoft', 'monitor'],
    ['computer', 'monitor'],
    ['internet', 'wifi'],
    ['software', 'code'],
    ['startup', 'rocket'],
    ['google', 'search'],
    ['amazon', 'shopping-cart'],
    ['apple', 'smartphone'],
    ['robot', 'bot'],
    ['digital', 'binary'],
    ['cyber', 'lock'],
    ['cloud', 'cloud'],
    ['chip', 'cpu'],
    ['hack', 'lock'],
    ['tech', 'cpu'],
    ['app', 'smartphone'],
    ['ai', 'brain-circuit'],
    ['data', 'database'],
    ['server', 'server'],
    ['network', 'network'],
    ['quantum', 'atom'],
    ['malware', 'bug'],
    ['phishing', 'fish'],
    ['privacy', 'eye-off'],
    ['encryption', 'lock'],
    ['semiconductor', 'cpu'],
    ['silicon', 'cpu'],
    ['nvidia', 'gpu'],
    ['tesla', 'car'],
    ['meta', 'glasses'],
    ['social media', 'share-2'],
    ['tiktok', 'video'],
    ['twitter', 'twitter'],
    ['facebook', 'facebook'],
    ['instagram', 'instagram'],
    ['streaming', 'tv'],

    // ── Sports ──
    ['championship', 'trophy'],
    ['tournament', 'trophy'],
    ['basketball', 'circle-dot'],
    ['football', 'goal'],
    ['volleyball', 'volleyball'],
    ['olympic', 'medal'],
    ['champion', 'trophy'],
    ['player', 'medal'],
    ['league', 'medal'],
    ['coach', 'whistle'],
    ['match', 'trophy'],
    ['score', 'target'],
    ['team', 'users'],
    ['game', 'gamepad-2'],
    ['win', 'trophy'],
    ['record', 'medal'],
    ['soccer', 'goal'],
    ['tennis', 'target'],
    ['baseball', 'target'],
    ['cricket', 'target'],
    ['rugby', 'goal'],
    ['swimming', 'waves'],
    ['marathon', 'footprints'],
    ['athlete', 'biceps-flexed'],
    ['stadium', 'landmark'],
    ['referee', 'flag'],
    ['injury', 'bandage'],
    ['transfer', 'arrow-right-left'],
    ['sponsor', 'handshake'],
    ['doping', 'syringe'],
    ['fitness', 'dumbbell'],
    ['boxing', 'hand-fist'],

    // ── Culture / Arts ──
    ['exhibition', 'palette'],
    ['celebrity', 'star'],
    ['festival', 'music'],
    ['concert', 'music'],
    ['theater', 'drama'],
    ['theatre', 'drama'],
    ['museum', 'palette'],
    ['singer', 'music'],
    ['director', 'clapperboard'],
    ['gallery', 'palette'],
    ['movie', 'clapperboard'],
    ['film', 'clapperboard'],
    ['book', 'book-open'],
    ['novel', 'book-open'],
    ['author', 'pen'],
    ['music', 'music'],
    ['art', 'palette'],
    ['award', 'trophy'],
    ['album', 'disc'],
    ['podcast', 'podcast'],
    ['fashion', 'shirt'],
    ['design', 'paintbrush'],
    ['sculpture', 'amphora'],
    ['photograph', 'camera'],
    ['dance', 'music-2'],
    ['opera', 'drama'],
    ['symphony', 'music'],
    ['grammy', 'trophy'],
    ['oscar', 'trophy'],
    ['emmy', 'trophy'],
    ['broadway', 'drama'],
    ['netflix', 'tv'],
    ['disney', 'castle'],
    ['hollywood', 'clapperboard'],
    ['bestseller', 'book-open'],
    ['streaming', 'play'],

    // ── Environment ──
    ['deforestation', 'tree-pine'],
    ['conservation', 'tree-deciduous'],
    ['sustainable', 'recycle'],
    ['renewable', 'wind'],
    ['greenhouse', 'thermometer'],
    ['pollution', 'cloud-fog'],
    ['emission', 'factory'],
    ['wildlife', 'bird'],
    ['climate', 'globe'],
    ['carbon', 'cloud'],
    ['recycle', 'recycle'],
    ['forest', 'tree-pine'],
    ['energy', 'zap'],
    ['solar', 'sun'],
    ['green', 'leaf'],
    ['ocean', 'waves'],
    ['species', 'bird'],
    ['coral', 'fish'],
    ['glacier', 'mountain-snow'],
    ['arctic', 'snowflake'],
    ['antarctic', 'snowflake'],
    ['biodiversity', 'trees'],
    ['extinct', 'skull'],
    ['ecosystem', 'leaf'],
    ['organic', 'sprout'],
    ['electric vehicle', 'zap'],
    ['wind farm', 'wind'],
    ['oil spill', 'droplets'],
    ['habitat', 'trees'],
    ['endangered', 'alert-triangle'],
    ['plastic', 'trash-2'],
    ['waste', 'trash-2'],
    ['compost', 'leaf'],

    // ── Science ──
    ['experiment', 'flask-conical'],
    ['laboratory', 'flask-conical'],
    ['scientist', 'atom'],
    ['discovery', 'search'],
    ['research', 'microscope'],
    ['biology', 'dna'],
    ['chemistry', 'flask-conical'],
    ['physics', 'atom'],
    ['quantum', 'atom'],
    ['gene', 'dna'],
    ['genome', 'dna'],
    ['study', 'microscope'],
    ['theory', 'atom'],
    ['lab', 'flask-conical'],
    ['nasa', 'rocket'],
    ['breakthrough', 'sparkles'],
    ['peer review', 'clipboard-check'],
    ['journal', 'book'],
    ['thesis', 'graduation-cap'],
    ['hypothesis', 'flask-conical'],
    ['particle', 'atom'],
    ['neuroscience', 'brain'],
    ['stem cell', 'dna'],
    ['fossil', 'bone'],
    ['archaeology', 'pickaxe'],
    ['paleontology', 'bone'],
    ['geology', 'mountain'],
    ['astronomy', 'telescope'],
    ['telescope', 'telescope'],
    ['microscope', 'microscope'],

    // ── Crime / Justice ──
    ['investigation', 'search'],
    ['detective', 'search'],
    ['shooting', 'alert-triangle'],
    ['evidence', 'fingerprint'],
    ['fingerprint', 'fingerprint'],
    ['murder', 'gavel'],
    ['prison', 'lock'],
    ['arrest', 'handcuffs'],
    ['police', 'siren'],
    ['crime', 'siren'],
    ['court', 'gavel'],
    ['trial', 'gavel'],
    ['guilty', 'gavel'],
    ['theft', 'lock'],
    ['fraud', 'alert-triangle'],
    ['suspect', 'search'],
    ['sentence', 'gavel'],
    ['jury', 'scale'],
    ['judge', 'gavel'],
    ['lawyer', 'scale'],
    ['attorney', 'scale'],
    ['prosecutor', 'gavel'],
    ['robbery', 'lock'],
    ['kidnapping', 'alert-triangle'],
    ['carjacking', 'car'],
    ['trafficking', 'alert-triangle'],
    ['smuggling', 'package'],
    ['assault', 'swords'],
    ['homicide', 'skull'],
    ['arson', 'flame'],
    ['vandalism', 'hammer'],
    ['drug cartel', 'skull'],
    ['mafia', 'skull'],
    ['gang', 'users'],
    ['inmate', 'lock'],
    ['parole', 'key'],
    ['bail', 'banknote'],
    ['witness', 'eye'],
    ['testimony', 'mic'],
    ['surveillance', 'cctv'],
    ['forensic', 'fingerprint'],

    // ── Disaster ──
    ['earthquake', 'alert-triangle'],
    ['tsunami', 'waves'],
    ['explosion', 'bomb'],
    ['catastrophe', 'alert-triangle'],
    ['avalanche', 'mountain-snow'],
    ['landslide', 'mountain'],
    ['collapse', 'alert-triangle'],
    ['disaster', 'flame'],
    ['emergency', 'siren'],
    ['evacuation', 'move-right'],
    ['death toll', 'skull'],
    ['rescue', 'life-buoy'],
    ['survivor', 'heart-pulse'],
    ['damage', 'alert-triangle'],
    ['destroyed', 'flame'],
    ['crash', 'alert-triangle'],
    ['derailment', 'train'],
    ['sinking', 'ship'],
    ['wreckage', 'alert-triangle'],
    ['blackout', 'power-off'],
    ['famine', 'wheat'],
    ['humanitarian crisis', 'heart-handshake'],

    // ── Diplomacy / International ──
    ['united nations', 'globe'],
    ['ambassador', 'globe'],
    ['diplomatic', 'handshake'],
    ['diplomat', 'handshake'],
    ['negotiate', 'handshake'],
    ['alliance', 'handshake'],
    ['treaty', 'scroll'],
    ['summit', 'globe'],
    ['nato', 'shield'],
    ['peace', 'heart-handshake'],
    ['refugee', 'tent'],
    ['humanitarian', 'heart-handshake'],
    ['asylum', 'tent'],
    ['migration', 'footprints'],
    ['immigrant', 'footprints'],
    ['border', 'fence'],
    ['embargo', 'ban'],
    ['sovereignty', 'crown'],
    ['annexation', 'flag'],
    ['occupation', 'shield'],
    ['ceasefire', 'handshake'],
    ['peacekeeping', 'shield-check'],
    ['aid', 'hand-helping'],
    ['relief', 'hand-helping'],
    ['extradition', 'plane'],
    ['consulate', 'building'],
    ['embassy', 'building'],

    // ── Education ──
    ['university', 'graduation-cap'],
    ['scholarship', 'medal'],
    ['graduation', 'graduation-cap'],
    ['professor', 'book-open'],
    ['education', 'book-open'],
    ['student', 'graduation-cap'],
    ['teacher', 'pencil'],
    ['college', 'graduation-cap'],
    ['academic', 'graduation-cap'],
    ['learning', 'book-open'],
    ['school', 'school'],
    ['degree', 'graduation-cap'],
    ['campus', 'school'],
    ['tuition', 'banknote'],
    ['curriculum', 'book-open'],
    ['exam', 'clipboard'],
    ['literacy', 'book-open'],
    ['kindergarten', 'baby'],
    ['library', 'library'],
    ['textbook', 'book'],
    ['lecture', 'presentation'],

    // ── Space ──
    ['astronaut', 'rocket'],
    ['spacecraft', 'rocket'],
    ['satellite', 'satellite-dish'],
    ['spacex', 'rocket'],
    ['space', 'rocket'],
    ['rocket', 'rocket'],
    ['orbit', 'orbit'],
    ['mars', 'globe'],
    ['moon', 'moon'],
    ['asteroid', 'star'],
    ['galaxy', 'sparkles'],
    ['cosmos', 'sparkles'],
    ['launch', 'rocket'],
    ['telescope', 'telescope'],
    ['comet', 'star'],
    ['nebula', 'sparkles'],
    ['constellation', 'star'],
    ['rover', 'bot'],
    ['probe', 'radar'],
    ['iss', 'satellite'],
    ['hubble', 'telescope'],
    ['james webb', 'telescope'],
    ['black hole', 'circle'],
    ['supernova', 'sparkles'],
    ['solar system', 'orbit'],
    ['exoplanet', 'globe'],

    // ── Countries / Regions ──
    ['iran', 'flag'],
    ['israel', 'flag'],
    ['china', 'flag'],
    ['russia', 'flag'],
    ['ukraine', 'flag'],
    ['america', 'flag'],
    ['usa', 'flag'],
    ['europe', 'globe'],
    ['africa', 'globe'],
    ['asia', 'globe'],
    ['india', 'flag'],
    ['japan', 'flag'],
    ['korea', 'flag'],
    ['britain', 'flag'],
    ['france', 'flag'],
    ['germany', 'flag'],
    ['brazil', 'flag'],
    ['australia', 'globe'],
    ['mexico', 'flag'],
    ['canada', 'flag'],
    ['turkey', 'flag'],
    ['saudi', 'flag'],
    ['syria', 'flag'],
    ['iraq', 'flag'],
    ['afghanistan', 'flag'],
    ['pakistan', 'flag'],
    ['egypt', 'flag'],
    ['nigeria', 'flag'],
    ['south africa', 'flag'],
    ['taiwan', 'flag'],
    ['philippines', 'flag'],
    ['indonesia', 'flag'],
    ['vietnam', 'flag'],
    ['thailand', 'flag'],
    ['poland', 'flag'],
    ['italy', 'flag'],
    ['spain', 'flag'],
    ['greece', 'flag'],
    ['norway', 'flag'],
    ['sweden', 'flag'],
    ['switzerland', 'flag'],
    ['netherlands', 'flag'],
    ['argentina', 'flag'],
    ['colombia', 'flag'],
    ['venezuela', 'flag'],
    ['cuba', 'flag'],
    ['middle east', 'globe'],
    ['latin america', 'globe'],
    ['caribbean', 'globe'],
    ['pacific', 'globe'],

    // ── Transport / Vehicles ──
    ['aircraft', 'plane'],
    ['airline', 'plane'],
    ['flight', 'plane'],
    ['aviation', 'plane'],
    ['plane', 'plane'],
    ['jet', 'plane'],
    ['ship', 'ship'],
    ['vessel', 'ship'],
    ['cargo', 'ship'],
    ['cruise', 'ship'],
    ['navy', 'ship'],
    ['port', 'anchor'],
    ['harbor', 'anchor'],
    ['submarine', 'ship'],
    ['train', 'train'],
    ['railway', 'train'],
    ['metro', 'train'],
    ['subway', 'train'],
    ['car', 'car'],
    ['vehicle', 'car'],
    ['traffic', 'traffic-cone'],
    ['highway', 'route'],
    ['truck', 'truck'],
    ['bus', 'bus'],
    ['taxi', 'car-taxi-front'],
    ['motorcycle', 'motorbike'],
    ['bicycle', 'bike'],
    ['boat', 'sailboat'],
    ['ferry', 'ship'],
    ['helicopter', 'plane'],
    ['tank', 'shield'],
    ['tractor', 'tractor'],

    // ── Buildings / Places ──
    ['skyscraper', 'building'],
    ['apartment', 'building'],
    ['housing', 'house'],
    ['factory', 'factory'],
    ['warehouse', 'warehouse'],
    ['hospital', 'hospital'],
    ['house', 'house'],
    ['home', 'house'],
    ['hotel', 'hotel'],
    ['building', 'building'],
    ['tower', 'antenna'],
    ['church', 'church'],
    ['mosque', 'landmark'],
    ['temple', 'landmark'],
    ['palace', 'castle'],
    ['castle', 'castle'],
    ['prison', 'lock'],
    ['jail', 'lock'],
    ['bridge', 'route'],
    ['dam', 'dam'],
    ['school', 'school'],
    ['university', 'school-2'],
    ['stadium', 'landmark'],
    ['airport', 'plane-takeoff'],
    ['restaurant', 'utensils'],
    ['supermarket', 'shopping-cart'],

    // ── Resources / Energy ──
    ['petroleum', 'fuel'],
    ['pipeline', 'fuel'],
    ['gasoline', 'fuel'],
    ['natural gas', 'flame'],
    ['electricity', 'zap'],
    ['power plant', 'factory'],
    ['nuclear power', 'radiation'],
    ['oil', 'fuel'],
    ['fuel', 'fuel'],
    ['coal', 'mountain'],
    ['mining', 'pickaxe'],
    ['lithium', 'battery'],
    ['battery', 'battery'],
    ['hydrogen', 'atom'],
    ['wind turbine', 'wind'],
    ['solar panel', 'sun'],
    ['dam', 'dam'],
    ['water', 'droplets'],
    ['irrigation', 'droplets'],
    ['wheat', 'wheat'],
    ['grain', 'wheat'],
    ['crop', 'wheat'],
    ['harvest', 'wheat'],
    ['food', 'utensils'],

    // ── Communication / Media ──
    ['television', 'tv'],
    ['broadcast', 'radio-tower'],
    ['journalist', 'newspaper'],
    ['newspaper', 'newspaper'],
    ['interview', 'mic'],
    ['press', 'newspaper'],
    ['media', 'camera'],
    ['photograph', 'camera'],
    ['video', 'video'],
    ['footage', 'video'],
    ['radio', 'radio'],
    ['signal', 'signal'],
    ['telephone', 'phone'],
    ['phone', 'phone'],
    ['mobile', 'smartphone'],
    ['email', 'mail'],
    ['speech', 'speech'],
    ['statement', 'mic'],
    ['announce', 'megaphone'],
    ['declare', 'megaphone'],
    ['report', 'newspaper'],
    ['headline', 'newspaper'],
    ['censorship', 'ban'],
    ['disinformation', 'alert-triangle'],
    ['propaganda', 'megaphone'],
    ['social media', 'share-2'],
    ['viral', 'share-2'],

    // ── Authority / Power ──
    ['king', 'crown'],
    ['queen', 'crown'],
    ['royal', 'crown'],
    ['prince', 'crown'],
    ['princess', 'crown'],
    ['emperor', 'crown'],
    ['monarch', 'crown'],
    ['pope', 'cross'],
    ['vatican', 'church'],
    ['religious', 'cross'],

    // ── People / Society ──
    ['children', 'baby'],
    ['women', 'user'],
    ['family', 'users'],
    ['community', 'users'],
    ['population', 'users'],
    ['worker', 'hard-hat'],
    ['employee', 'briefcase'],
    ['homeless', 'tent'],
    ['poverty', 'hand-coins'],
    ['inequality', 'scale'],
    ['rights', 'scale'],
    ['freedom', 'key'],
    ['democracy', 'vote'],
    ['justice', 'scale'],
    ['victim', 'heart'],
    ['survivor', 'heart-pulse'],
    ['hero', 'shield'],
    ['leader', 'crown'],
    ['celebrity', 'star'],
    ['billionaire', 'gem'],
    ['ceo', 'briefcase'],
    ['founder', 'lightbulb'],
    ['entrepreneur', 'lightbulb'],

    // ── Food / Agriculture ──
    ['agriculture', 'tractor'],
    ['farming', 'tractor'],
    ['livestock', 'beef'],
    ['fishing', 'fish'],
    ['restaurant', 'utensils'],
    ['cuisine', 'chef-hat'],
    ['coffee', 'coffee'],
    ['wine', 'wine'],
    ['beer', 'beer'],
    ['organic food', 'salad'],

    // ── Nature / Animals ──
    ['volcano', 'mountain'],
    ['eruption', 'mountain'],
    ['earthquake', 'activity'],
    ['mountain', 'mountain'],
    ['river', 'waves'],
    ['lake', 'waves'],
    ['desert', 'sun'],
    ['jungle', 'trees'],
    ['island', 'palmtree'],
    ['beach', 'palmtree'],
    ['whale', 'fish'],
    ['shark', 'fish'],
    ['bear', 'paw-print'],
    ['wolf', 'paw-print'],
    ['lion', 'paw-print'],
    ['eagle', 'bird'],
    ['snake', 'bug'],
    ['insect', 'bug'],
    ['pet', 'paw-print'],
    ['dog', 'dog'],
    ['cat', 'cat'],

    // ── Time / Urgency ──
    ['deadline', 'clock'],
    ['urgent', 'alarm-clock'],
    ['breaking', 'zap'],
    ['update', 'refresh-cw'],
    ['tonight', 'moon'],
    ['morning', 'sunrise'],
    ['today', 'calendar'],
    ['tomorrow', 'calendar'],
    ['yesterday', 'calendar'],
    ['annual', 'calendar'],
    ['weekly', 'calendar'],
    ['daily', 'calendar'],

    // ── Death / Mortality ──
    ['death', 'skull'],
    ['killed', 'skull'],
    ['dead', 'skull'],
    ['died', 'skull'],
    ['fatal', 'skull'],
    ['casualty', 'skull'],
    ['casualties', 'skull'],
    ['funeral', 'cross'],
    ['burial', 'cross'],
    ['mourning', 'heart'],

    // ── General Actions ──
    ['warning', 'alert-triangle'],
    ['crisis', 'alert-triangle'],
    ['ban', 'ban'],
    ['approval', 'check'],
    ['sign', 'pen'],
    ['announce', 'megaphone'],
    ['reveal', 'eye'],
    ['discover', 'search'],
    ['launch', 'rocket'],
    ['open', 'door-open'],
    ['close', 'door-closed'],
    ['begin', 'play'],
    ['end', 'square'],
    ['win', 'trophy'],
    ['lose', 'thumbs-down'],
    ['success', 'check'],
    ['failure', 'x'],
    ['grow', 'trending-up'],
    ['decline', 'trending-down'],
    ['rise', 'arrow-up'],
    ['fall', 'arrow-down'],
    ['increase', 'arrow-up'],
    ['decrease', 'arrow-down'],
    ['expand', 'maximize'],
    ['shrink', 'minimize'],
    ['build', 'hammer'],
    ['destroy', 'flame'],
    ['create', 'plus'],
    ['remove', 'minus'],
    ['change', 'refresh-cw'],
    ['new', 'sparkles'],
    ['old', 'clock'],
];

/** A keyword match with position and matched text span */
export interface KeywordMatch {
    icon: string;
    pos: number;
    length: number;
}

/**
 * Find keyword→icon matches in a headline with positions and lengths.
 * Used by the text renderer to replace words with inline icons.
 */
export function findKeywordMatches(title: string, maxMatches = 12): KeywordMatch[] {
    const lower = title.toLowerCase();
    const matched: KeywordMatch[] = [];

    for (const [keyword, iconName] of KEYWORD_ICONS) {
        const idx = lower.indexOf(keyword);
        if (idx < 0) continue;
        // Check no overlap with existing matches
        const end = idx + keyword.length;
        const overlaps = matched.some(m => !(end <= m.pos || idx >= m.pos + m.length));
        if (overlaps) continue;
        matched.push({ icon: iconName, pos: idx, length: keyword.length });
        if (matched.length >= maxMatches) break;
    }

    matched.sort((a, b) => a.pos - b.pos);
    return matched;
}

/**
 * Extract an ordered sequence of Lucide icon names from a headline.
 * Returns icons in the order their keywords appear in the text.
 */
export function headlineToLucideIcons(title: string, maxIcons = 12): string[] {
    const lower = title.toLowerCase();
    const matched: { icon: string; pos: number }[] = [];
    const usedPositions = new Set<number>(); // avoid overlapping matches

    for (const [keyword, iconName] of KEYWORD_ICONS) {
        const idx = lower.indexOf(keyword);
        if (idx >= 0 && !usedPositions.has(idx)) {
            matched.push({ icon: iconName, pos: idx });
            usedPositions.add(idx);
        }
    }

    // Sort by position in headline (narrative order)
    matched.sort((a, b) => a.pos - b.pos);

    // Deduplicate consecutive same icons
    const result: string[] = [];
    for (const m of matched) {
        if (result.length === 0 || result[result.length - 1] !== m.icon) {
            result.push(m.icon);
        }
        if (result.length >= maxIcons) break;
    }

    return result;
}

/**
 * Get a set of theme-default icons when no keywords match.
 */
const THEME_FALLBACK_ICONS: Record<string, string[]> = {
    conflict: ['swords', 'shield', 'bomb'],
    economy: ['coins', 'chart-line', 'banknote'],
    weather: ['cloud-lightning', 'sun', 'wind'],
    health: ['heart-pulse', 'syringe', 'stethoscope'],
    politics: ['landmark', 'vote', 'gavel'],
    technology: ['cpu', 'brain-circuit', 'code'],
    sports: ['trophy', 'medal', 'goal'],
    culture: ['palette', 'music', 'clapperboard'],
    environment: ['leaf', 'tree-pine', 'recycle'],
    science: ['atom', 'flask-conical', 'microscope'],
    crime: ['siren', 'gavel', 'fingerprint'],
    disaster: ['flame', 'alert-triangle', 'siren'],
    diplomacy: ['handshake', 'globe', 'scroll'],
    education: ['graduation-cap', 'book-open', 'school'],
    space: ['rocket', 'telescope', 'orbit'],
    general: ['newspaper', 'globe', 'zap'],
};

/**
 * Get icon names for a headline, with theme-based fallback.
 */
export function getHeadlineIcons(
    title: string,
    theme: string,
    maxIcons = 12,
): string[] {
    const icons = headlineToLucideIcons(title, maxIcons);
    if (icons.length >= 3) return icons;

    // Pad with theme fallback icons
    const fallback = THEME_FALLBACK_ICONS[theme] ?? THEME_FALLBACK_ICONS.general;
    for (const fb of fallback) {
        if (!icons.includes(fb)) icons.push(fb);
        if (icons.length >= maxIcons) break;
    }
    return icons;
}
